apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: roboshop

  labels:
    purpose: pod
    environment: prod

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80