apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins.url: "http://joindevops.com/jekins/build/test5"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80