apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    project: roboshop
spec:
  containers:
  - name: nginxx
    image: nginx
    env:
    - name: course
      value: "kubernetes"
    - name: trainer
      value: "kiran"