apiVersion: v1
kind: Service
metadata:
  name: service-np
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    component: frontend
    purpose: service-np
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80