apiVersion: v1
kind: Service
metadata:
  name: service-lb-demo
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    component: frontend
    purpose: loadbalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007