apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: rs
spec:
  replicas: 5
  selector:
    matchLabels: 
      project: roboshop
      purpose: rs
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs
    spec:
      containers:
      - name: nginx
        image: nginx
